# Usar imagem oficial do Nginx
FROM nginx:alpine

# Copiar o arquivo de configuração do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiar o código do Laravel para dentro do contêiner
COPY ./brutos /var/www

# Expor porta 80 para o Nginx
EXPOSE 80
