services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exemplo-app
    working_dir: /var/www/html
    volumes:
      - ./servindo:/var/www/html
      - ./brutos:/home
    ports:
      - "6001:8000"
    networks:
      - exemplo_network
    depends_on:
      - postgres
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=
    command: >
      sh -c "composer create-project --prefer-dist laravel/laravel . 
      && cp -r /home/. /var/www/html/
      && php artisan serve --host=0.0.0.0 --port=8000"


  postgres:
    image: postgres:15
    container_name: exemplo-postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: exemplo
      POSTGRES_PASSWORD: exemplo
      POSTGRES_DB: exemplo_db
    ports:
      - "6002:5432" # Banco de dados
    networks:
      - exemplo_network

networks:
  exemplo_network:
    driver: bridge
