version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile.prod
    container_name: tinder-app-prod
    working_dir: /var/www
    depends_on:
      - db
    env_file:
      - .env.prod

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: tinder-nginx-prod
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:17
    container_name: tinder-postgres-prod
    restart: always
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tinder
      POSTGRES_USER: tinder_user
      POSTGRES_PASSWORD: s3cret-prod
    ports:
      - "5432:5432"

volumes:
  pg_data_prod:
